apiVersion: v2
name: crossplane
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: crossplane
    version: 2.2.0
    repository: https://charts.crossplane.io/stable
