providers:
  kubernetes:
    image:
      repository: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      tag: v1.3.0@sha256:53cdc7739734ec4e48b339d5fa950d8e049ee457e30895666f431d8a3de7d3b1
  github:
    image:
      repository: xpkg.upbound.io/coopnorge/provider-github
      tag: v0.13.0@sha256:216108c2afc9fe7dbba0933a158876dfd154fa07d5696b97318f68fb2e1879ac
  minio:
    image:
      repository: xpkg.upbound.io/vshn/provider-minio
      tag: v0.4.5@sha256:7af4d9157ece100c28767942a1b61445b56cbb071abd71033a4c5947335ffff7

functions:
  auto-ready:
    image:
      repository: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      tag: v0.7.0@sha256:989e7bb4704859cbd6475cc61255b4b4ad53483ea43f3d2d1e4be5e3ff678869
  go-templating:
    image:
      repository: xpkg.upbound.io/crossplane-contrib/function-go-templating
      tag: v0.12.3@sha256:d0585f97011b2967add83d9c606bcd27c48f69963ba1f136ab6f0de214447421
  patch-and-transform:
    image:
      repository: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      tag: v0.10.8@sha256:dbef22fbd2a4e117d4289b6e787ba92f0f6477bd0955ba816290c5f87a3ae758
  status-transformer:
    image:
      repository: xpkg.upbound.io/crossplane-contrib/function-status-transformer
      tag: v0.5.2@sha256:aa34abe22b1585f8670a64cdb3d2056df8ba4b6d3a7ce48f801ab81daef31785

github:
  enabled: true
  claim:
    enabled: true

minio:
  enabled: true
