---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: github-repo
  labels:
    provider: azure
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: bakito.net/v1alpha1
    kind: GithubRepo
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      step: patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: metadata
            patches:
              - fromFieldPath: metadata.annotations
                toFieldPath: metadata.annotations
              - fromFieldPath: spec.name
                toFieldPath: metadata.name
          - name: repo-name
            patches:
              - fromFieldPath: spec.name
                toFieldPath: spec.forProvider.name
        resources:
          - name: repo
            base:
              apiVersion: repo.github.upbound.io/v1alpha1
              kind: Repository
              spec:
                forProvider:
                  visibility: public
                  autoInit: true
                providerConfigRef:
                  name: default
            patches:
              - type: PatchSet
                patchSetName: metadata
              - type: PatchSet
                patchSetName: repo-name
    - functionRef:
        name: function-go-templating
      step: branches
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ range .observed.composite.resource.spec.branches }}
            {{- if ne . "main" }}
            ---
            apiVersion: repo.github.upbound.io/v1alpha1
            kind: Branch
            metadata:
              name: {{ $.observed.composite.resource.spec.name }}-{{ . }}
              annotations:
                crossplane.io/external-name: {{ $.observed.composite.resource.spec.name }}:{{ . }}
                gotemplating.fn.crossplane.io/composition-resource-name: {{ $.observed.composite.resource.spec.name }}-{{ . }}
            spec:
              forProvider:
                branch: {{ . }}
                repositoryRef:
                  name: {{ $.observed.composite.resource.spec.name }}
              providerConfigRef:
                name: default
            {{ end }}
            {{ end }}
    - functionRef:
        name: function-auto-ready
      step: automatically-detect-ready-composed-resources

