---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: githubrepos.bakito.net
spec:
  group: bakito.net
  names:
    kind: GithubRepo
    plural: githubrepos
  claimNames:
    kind: GithubRepoClaim
    plural: githubrepoclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Repo Name
                branches:
                  description: The list of branches.
                  type: array
                  items:
                    type: string
              required:
                - name
