{{-  if  (and .Values.github.enabled .Values.github.claim.enabled) }}
apiVersion: bakito.net/v1alpha1
kind: GithubRepoClaim
metadata:
  name: xsd-repo
  namespace: postgresql
spec:
  name: xsd-repo
  branches:
    - main
    - foo
{{- end }}
