{{-  if .Values.github.enabled }}
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: credentials
      name: github-creds
      namespace: crossplane-system
    source: Secret
{{- end }}
