{{-  if .Values.github.enabled }}
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: credentials
      name: github-creds
      namespace: {{ .Release.Namespace }}
    source: Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
